### ISSUE TITLE
Can't PUT to update Annotation Set

### ISSUE THREAD

**Issue by stain** [Annotopia/Annotopia#16]
If I retrieve an annotation set:

```
}stain@biggie-utopic:~/src/annotopia/utopia-tests$ curl "http://localhost:8080/s/annotationset/3B1DA1C4-0112-44A4-ACA1-C60D40B14C03?apiKey=$API" > loop; 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1793    0  1793    0     0  22295      0 --:--:-- --:--:-- --:--:-- 22412
```

```
stain@biggie-utopic:~/src/annotopia/utopia-tests$ cat loop 
{
  "@graph" : [ {
    "@id" : "http://localhost:8080/s/annotation/F428F1FE-98EA-4F4B-A512-0601881611BC",
    "@type" : "http://www.w3.org/ns/oa#Annotation",
    "lastUpdateOn" : "2015-03-23T15:59:01+0000",
    "previousVersion" : "3693262aeb4c99d83c829608f7fb5973",
    "hasBody" : "http://localhost:8080/s/content/59212838-4B0C-49E5-ABC5-F04C2BEAD6CA",
    "hasTarget" : "http://example.com/page5"
  }, {
    "@id" : "http://localhost:8080/s/annotationset/3B1DA1C4-0112-44A4-ACA1-C60D40B14C03",
    "@type" : "http://purl.org/annotopia#AnnotationSet",
    "annotations" : "http://localhost:8080/s/annotation/F428F1FE-98EA-4F4B-A512-0601881611BC",
    "lastUpdateOn" : "2015-03-23T15:59:01+0000",
    "previousVersion" : "blank",
    "version" : "1",
    "label" : "Utopia set"
  }, {
    "@id" : "http://localhost:8080/s/content/59212838-4B0C-49E5-ABC5-F04C2BEAD6CA",
    "@type" : [ "http://purl.org/dc/dcmitype/Text", "http://www.w3.org/2011/content#ContentAsText" ],
    "format" : "text/plain",
    "previousVersion" : "blank",
    "chars" : "this is another example for page 5"
  } ],
  "@id" : "urn:x-arq:DefaultGraphNode",
  "@context" : {
    "annotations" : {
      "@id" : "http://purl.org/annotopia#annotations",
      "@type" : "@id"
    },
    "lastUpdateOn" : "http://purl.org/pav/lastUpdateOn",
    "previousVersion" : "http://purl.org/pav/previousVersion",
    "version" : "http://purl.org/pav/version",
    "label" : "http://www.w3.org/2000/01/rdf-schema#label",
    "hasTarget" : {
      "@id" : "http://www.w3.org/ns/oa#hasTarget",
      "@type" : "@id"
    },
    "hasBody" : {
      "@id" : "http://www.w3.org/ns/oa#hasBody",
      "@type" : "@id"
    },
    "chars" : "http://www.w3.org/2011/content#chars",
    "format" : "http://purl.org/dc/elements/1.1/format"
  }
}
```

But PUT-ing it back does not work, even if I add the `apiKey` URL parameter

```

stain@biggie-utopic:~/src/annotopia/utopia-tests$ curl -v -X PUT "http://localhost:8080/s/annotationset/3B1De: application/json" -d@loop4C03?apiKey=$API" -H"Content-Type
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> PUT /s/annotationset/3B1DA1C4-0112-44A4-ACA1-C60D40B14C03?apiKey=164bb0e0-248f-11e4-8c21-0800200c9a66 HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:8080
> Accept: */*
> Content-Type: application/json
> Content-Length: 1749
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
< HTTP/1.1 401 Unauthorized
* Server Apache-Coyote/1.1 is not blacklisted
< Server: Apache-Coyote/1.1
< Content-Type: text/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Mon, 23 Mar 2015 16:22:35 GMT
* HTTP error before end of send, stop sending
< 
* Closing connection 0
{"message":"Api Key missing or invalid","status":"rejected"}
```

Am I meant to edit the JSON-LD to add the apiKey there?  (that works, but ends up with 200 OK error message instead, see #12 )

**Comment by stain** [comment]
If I wrap the JSON-LD in `set={ .. }`, I get a different error:

```
-&gt;&gt;  662 | updateAnnotationSet in AnnotationIntegratedStorageService.groovy
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    420 | doCall              in AnnotationIntegratedController.groovy
|    200 | doFilter . . . . .  in PageFragmentCachingFilter.java
|     63 | doFilter            in AbstractFilter.java
|     53 | doFilter . . . . .  in GrailsAnonymousAuthenticationFilter.java
|     49 | doFilter            in RequestHolderAuthenticationFilter.java
|     82 | doFilter . . . . .  in MutableLogoutFilter.java
|   1145 | runWorker           in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run                 in java.lang.Thread
</pre>
		
	
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;">Loading&hellip;</div>
		
		<script src="/static/js/application.js" type="text/javascript" ></script>

	</body>
</html>
* Closing connection 0

```

**Comment by stain** [comment]
```
34:20,001 ERROR GrailsExceptionResolver NullPointerException occurred when processing request: [PUT] /s/annotationset/3B1DA1C4-0112-44A4-ACA1-C60D40B14C03 - parameters:
apiKey: 164bb0e0-248f-11e4-8c21-0800200c9a66
Cannot invoke method size() on null object. Stacktrace follows:
java.lang.NullPointerException: Cannot invoke method size() on null object
	at org.annotopia.grails.services.storage.jena.integrated.AnnotationIntegratedStorageService.updateAnnotationSet(AnnotationIntegratedStorageService.groovy:662)
	at org.annotopia.grails.controllers.annotation.integrated.AnnotationIntegratedController$_closure3.doCall(AnnotationIntegratedController.groovy:420)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:200)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
	at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)
	at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by stain** [comment]
It seems to expect a fixed JSON structure

```groovy
					Object json = JsonUtils.fromString(set);
				    List array = json.getAt("annotations");

```

**Comment by stain** [comment]
Even with `annotations` as a JSON array, and the JSON-LD wrapped under `sets` (which is counter-intuitive for PUT), it does correctly add the annotation as a new graph, but does not update the `annotations` link. 

```
curl -v -XPUT -H"Content-Type: application/json" -d@annotation-set-update2.json http://localhost:8080/s/annotationset/8C722E32-6E63-4517-907E-3A2899FAA321
```

```json
{
    "apiKey": "164bb0e0-248f-11e4-8c21-0800200c9a66",
    "set": {
        "@context": "https://rawgit.com/Annotopia/AtSmartStorage/master/web-app/data/AnnotopiaContext.json",
        "@id": "http://localhost:8080/s/annotationset/8C722E32-6E63-4517-907E-3A2899FAA321",
        "@type": "at:AnnotationSet",
        "label": "Utopia set",
        "annotations": [ 
            { "@id": "urn:uuid:8e8d3ebf-c696-45be-8d1f-9df860c359ea",
              "@type": "oa:Annotation",
              "hasBody": [
                  {
                      "@type": [
                          "cnt:ContentAsText",
                          "dctypes:Text"
                      ],
                      "format": "text/plain",
                      "chars": "this is yet another example for page 7"
                  }
              ],
              "hasTarget": [
                  {
                      "@id": "urn:uuid:0352648d-c80d-465d-a01a-c5dff31d4601",
                      "@type": "oa:SpecificResource",
                      "hasSource": {
                          "@id": "https://example.com/page5",
                          "@type": "dctypes:Text",
                          "format": "text/html"
                      },
                      "hasSelector": {
                          "@type": "oa:TextQuoteSelector",
                          "exact": "page 7",
                          "prefix": "This example is from ",
                          "suffix": " at example.com"
                      }
                  }
              ]
          }
        ]
    }
}
```

**Comment by stain** [comment]
The controller requires `http://purl.org/annotopia#hasChanged` to be set to `true` on the `oa:Annotation`. I propose to rewrite this fully as it is not implementing `PUT` by any measure.

**Comment by paolociccarese** [comment]
That was a leftover related to the old Domeo server. I agree with a more
RESTful approach which makes more sense at this point. That will require
some changes in Domeo.

**Comment by stain** [comment]
I think this functionality COULD be kept, but then as a PATCH or POST call. Also I need to investigate further what happens to the existing non-updated annotations..

**Comment by paolociccarese** [comment]
The logic should keep the other annotations. Deletion is also a flag. The
deleted annotation is sent in for the server to detect it in storage and
wipe it out

**Comment by paolociccarese** [comment]
Also, I would create a brand new controller so that Domeo keeps working in
the meanwhile. Then we swap
