### ISSUE TITLE
Support micropublications

### ISSUE THREAD

**Issue by stain** [Annotopia/Annotopia#22]
Nano- and [micropublications](http://dx.doi.org/10.1186/2041-1480-5-28) require multiple named graphs, which is not currently supported.

See https://gist.github.com/stain/df47152577bde104b4bd#file-micropublications-1-annotation-jsonld for an example annotation with a micropublication in JSON-LD format.

Note that the exact relation between an `oa:Annotation` and a `mp:Micropublication` is still to be clarified, in the above example I assumed the annotation would take its `oa:hasTarget` to be equal the `mp:represents` of the micropublications - however I made a dummy body which also is a named graph that just declares the two authors -- the micropublication itself is defined in its own graph. This reflects how the structure was in the paper's N3 example -- however a better structure is probably to make the micropublication be the body of the annotation directly - this might however lead to a strange situation where only some of the graph IDs are rewritten.

(It is also unclear if graph IDs within a micropublication should be rewritten.)

Anyway - trying to add this to an annotation set:

```
curl -i -H "Authorization: annotopia-api-key 164bb0e0-248f-11e4-8c21-0800200c9a66"   \
    -H "Content-Type: application/json"       \
    -X POST http://annotopia.cs.man.ac.uk:80/s/annotationset/187FDE5F-4CEB-41BB-8639-9EE6FC153CEC/annotations/ \
    -d@micropublications-1-annotation.jsonld
```

Fails:

```
30:56,762  INFO ApiKeyAuthenticationService New-> Validating API key [164bb0e0-248f-11e4-8c21-0800200c9a66] on request from IP: 92.221.123.83
30:56,768  INFO SystemsService Validating API key [164bb0e0-248f-11e4-8c21-0800200c9a66]
30:56,771  INFO OpenAnnotationSetRESTController API key [164bb0e0-248f-11e4-8c21-0800200c9a66]
30:56,774  INFO OpenAnnotationSetRESTController Annotation set URI: http://annotopia.cs.man.ac.uk:80/s/annotationset/187FDE5F-4CEB-41BB-8639-9EE6FC153CEC
30:56,775  INFO AnnotationIntegratedStorageService [164bb0e0-248f-11e4-8c21-0800200c9a66] Retrieving annotation set http://annotopia.cs.man.ac.uk:80/s/annotationset/187FDE5F-4CEB-41BB-8639-9EE6FC153CEC
30:56,785  INFO JenaVirtuosoStoreService [164bb0e0-248f-11e4-8c21-0800200c9a66] Retrieving graph: http://annotopia.cs.man.ac.uk:80/s/graph/30B56404-0B72-47BA-BAFF-E03D3AD9E950
30:57,867  INFO JenaUtilsService [164bb0e0-248f-11e4-8c21-0800200c9a66] Named Graphs detection...
30:57,870  INFO JenaUtilsService [164bb0e0-248f-11e4-8c21-0800200c9a66] Named Graphs detected 6
30:57,870  INFO OpenAnnotationUtilsService [164bb0e0-248f-11e4-8c21-0800200c9a66] Detection of Annotation in Default Graph...
30:57,872  INFO OpenAnnotationUtilsService [164bb0e0-248f-11e4-8c21-0800200c9a66] Annotation in Default Graph detected 1
30:57,872  INFO OpenAnnotationUtilsService [164bb0e0-248f-11e4-8c21-0800200c9a66] Detection of Annotation in Named Graphs...
30:57,873  INFO OpenAnnotationUtilsService [164bb0e0-248f-11e4-8c21-0800200c9a66] Annotation graphs 0
30:57,873  INFO OpenAnnotationUtilsService [164bb0e0-248f-11e4-8c21-0800200c9a66] Annotation target detection...
30:57,875  INFO OpenAnnotationUtilsService [164bb0e0-248f-11e4-8c21-0800200c9a66] Identifiable Annotation targets 1
30:57,875  INFO OpenAnnotationStorageService [164bb0e0-248f-11e4-8c21-0800200c9a66] Multiple Annotation graphs detected... request rejected.
30:57,880 ERROR GrailsExceptionResolver StoreServiceException occurred when processing request: [POST] /s/annotationset/187FDE5F-4CEB-41BB-8639-9EE6FC153CEC/annotations/
{"message":"The request carries multiple Annotations or Annotation Graphs","duration":"1116ms","status":"nocontent"}. Stacktrace follows:
org.annotopia.groovy.service.store.StoreServiceException: {"message":"The request carries multiple Annotations or Annotation Graphs","duration":"1116ms","status":"nocontent"}
	at org.annotopia.grails.services.storage.jena.openannotation.OpenAnnotationStorageService.saveAnnotationDataset(OpenAnnotationStorageService.groovy:316)
	at org.annotopia.grails.controllers.openannotationset.OpenAnnotationSetRESTController$_closure2.doCall(OpenAnnotationSetRESTController.groovy:92)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:200)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
	at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)
	at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:82)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by stain** [comment]
It is also unclear if/why Micropublications needs to be split into multiple graphs - as a model it is highly structured and fits well within a single JSON-LD object:

```
{
   "@context":"https://raw.githubusercontent.com/Annotopia/AtSmartStorage/master/web-app/data/OAContext.json",
   "@id":"urn:uuid:a3e0f90e-a520-4764-ac0e-1642649d8f60",
   "@type":"oa:Annotation",
   "hasBody":

{
  "@context": {
    "mp": "http://purl.org/mp/",
    "ex": "http://www.example.com/micropublication/ex1/",
    "dct": "http://purl.org/dc/terms/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfg": "http://www.w3.org/2004/03/trix/rdfg-1/",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "prov": "http://www.w3.org/ns/prov#",
    "obo": "http://purl.obolibrary.org/obo#",
    "foaf": "http://xmlns.com/foaf/spec/0.98#",
    "mp:asserts": {
      "@type": "@id"
    },
    "mp:argues": {
      "@type": "@id"
    },
    "mp:hasAttribution": {
      "@type": "@id"
    },
    "mp:attributionOfAgent": {
      "@type": "@id"
    },
    "mp:qualifiedBy": {
      "@type": "@id"
    },
    "mp:supportedBy": {
      "@type": "@id"
    },
    "mp:quotes": {
      "@type": "@id"
    },
    "mp:represents": {
      "@type": "@id"
    },
    "mp:atTime": {
      "@type": "xsd:dateTime"
    }
  },
      "@id": "ex:MP1",
      "@type": "mp:Micropublication",
      "mp:argues": "ex:C1",
      "mp:asserts": [
        "ex:A_C1",
        "ex:Ref5",
        {
          "@id": "ex:C1",
          "@type": "mp:Claim",
          "mp:hasAttribution": "ex:A_C1",
          "mp:qualifiedBy": [
            "obo:CHEBI_68481",
            "obo:INO_0000736"
          ],
          "mp:statement": "Rapamycin [is] an inhibitor of the mTOR pathway.",
          "mp:supportedBy": {
            "@id": "ex:Ref5",
            "@type": "mp:Reference",
            "mp:citation": "Harrison et al. Nature 2009, 460(7253):392-395.",
            "mp:hasAttribution": {
              "@id": "ex:A_C1",
              "@type": "mp:Attribution",
              "mp:atTime": "2010-01-01T00:00:00Z",
              "mp:attributionOfAgent": {
                "@id" : "ex:SpilmanP",
                "@type" : [ "foaf:Person", "prov:Person", "mp:Agent" ],
                "mbox_sha1sum" : "6b4cacd4bc4de8d5d45903c29dec30eba1d696d3",
                "name" : "Patricia Spilman"
              },
              "rdfs:label": "A_C1: C1 authorship attribution"
            },
            "rdfs:label": "Ref5: Harrison et al. 2009"
          },
          "rdfs:label": "C1: Rapamycin inhibits mTOR"
        }
      ],
      "mp:attributionAsAuthor": {
        "@id": "ex:A_MP1",
        "@type": "mp:Attribution",
        "mp:atTime": "2013-08-01T00:00:00Z",
        "mp:attributionOfAgent":  {
            "@id" : "ex:ClarkT",
            "@type" : [ "foaf:Person", "prov:Person", "mp:Agent" ],
            "mbox_sha1sum" : "d9c9efcbcb2877d085cff13ec8b748772fec0ed6",
            "name" : "Tim Clark"
        },
        "rdfs:label": "A_MP1: MP1 authorship attribution"
      },
      "mp:quotes": [
        "obo:INO_0000736",
        "obo:CHEBI_9168"
      ],
      "mp:represents": "http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2848616",
      "rdfs:label": "MP1: MP Example 1"
},

   "motivatedBy":"oa:describing",
   "annotatedBy": {
      "@id":"http://orcid.org/0000-0001-9842-9718",
      "@type":"foaf:Person",
      "foaf:name":"Stian Soiland-Reyes"
   },
   "annotatedAt":"2015-05-20T01:17:00+0200",
   "serializedBy": "http://orcid.org/0000-0001-9842-9718",
   "serializedAt":"2015-05-20T01:17:00+0200",
   "hasTarget": "http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2848616"
}
```

`POST`ing the above seems to work at first, but it strangely returns an annotation set which includes:

```
   "hasBody" : null,
```

However, asking for the particular annotation (e.g. http://annotopia.cs.man.ac.uk:80/s/annotation/68AF4F6B-5103-4BC5-92A4-84AEBBD9528C) gives back the same information (but in a very different JSON structure)

**Comment by stain** [comment]
See suggested solutions in the proposed [workplan](https://docs.google.com/document/d/1bRPswmitPPufVKSQDHRXVPt4zIxTXBL-6S5N2lKK7MQ/edit?usp=sharing).

We'll go for a mid-approach where Domeo creates [micropublications as in the ElasticSearch version](https://gist.github.com/stain/96d4c86663ba275c447f), but updated to be wrapped as an `oa:Annotation` rather than `ao:*`. This is a single-graph micropublication model, which is easier to handle on the Annotopia side, and should be storable with the current Annotation Set API (but see  `hasBody: null` problem above).  The annotation body in JSON will be additionally stored byte-equal as a file on disk/database, or as an additional (hidden in a annotopia-specific graph) literal in the triple store.

For retrieval of micropublications for a given document, a new API method will be added that looks up `oa:Annotation` that are also (alternatively: which has a body that is) an `mp:Micropublication`, then these are merged/combined, either from building a merged graph of those annotations, or by loaded the previously POSTed JSON from disk or literals in a side-graph.

**Comment by stain** [comment]
Suggested API will be detailed in https://github.com/Annotopia/Annotopia/wiki/Micropublications-API

**Comment by stain** [comment]
@fbacall found out why there was the `hasBody: null` problem:

> the body needs to have type `cnt:ContentAsText`
> or it won't save
> if i add that type (along with `mp:Micropublication`), it saves OK
> https://gist.github.com/fbacall/336b7aff1cfe8a4c918c

**Comment by stain** [comment]
Domeo's current implementation for serialization of micropublications: https://github.com/domeo/DomeoClient/tree/master/src/org/mindinformatics/gwt/domeo/plugins/annotation/micropubs/serialization
